baseURL = 'http://www.taoky.moe/TAsterisk'
theme = "ananke"
title = 'TAsterisk'
defaultContentLanguage = 'zh'
canonifyurls = "true"
copyright = "CC-BY-NC-SA 4.0"
hasCJKLanguage = true

[author]
name = "taoky"

[languages]

[languages.en]
weight = 1
languageCode = "en-us"

[[languages.en.params.ananke_socials]]
name = "rss"
url = "https://www.taoky.moe/TAsterisk/en/index.xml"

[languages.zh]
weight = 2
languageCode = "zh-cn"

[languages.zh.params]
date_format = "2006 年 1 月 2 日"
background_color_class = "bg-blue"

[[languages.zh.params.ananke_socials]]
name = "rss"
url = "https://www.taoky.moe/TAsterisk/index.xml"

[params]
# show_reading_time = true
custom_css = ["alert.css", "override.css"]

[[languages.en.params.ananke_socials]]
name = "github"
url = "https://github.com/taoky/TAsterisk"

[[languages.zh.params.ananke_socials]]
name = "github"
url = "https://github.com/taoky/TAsterisk"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
